apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: portfolio-services
    app.kubernetes.io/part-of: devops-portfolio
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Application source
  source:
    repoURL: https://github.com/your-username/devops-portfolio  # Replace with your repo
    targetRevision: main
    path: k8s-manifests
    
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-portfolio
    
  # Project
  project: default
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true      # Automatically remove resources
      selfHeal: true   # Automatically sync when cluster state deviates
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
        
  # Ignore differences for dynamic fields
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    
  # Health check configuration
  revisionHistoryLimit: 10
  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-user-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: portfolio-user-service
    app.kubernetes.io/part-of: devops-portfolio
    app.kubernetes.io/component: user-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/your-username/devops-portfolio  # Replace with your repo
    targetRevision: main
    path: gitops/manifests/user-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-portfolio
    
  project: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
        
  # Resource health check
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    - /status
    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-order-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: portfolio-order-service
    app.kubernetes.io/part-of: devops-portfolio
    app.kubernetes.io/component: order-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/your-username/devops-portfolio  # Replace with your repo
    targetRevision: main
    path: gitops/manifests/order-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-portfolio
    
  project: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
        
  # Dependency on user service
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    - /status 