apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      disableRecordingRules: false
    secureJsonData: {}
    version: 1

  - name: Prometheus-Alertmanager
    type: prometheus
    access: proxy
    url: http://alertmanager-service:9093
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      manageAlerts: false
      prometheusType: Prometheus
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://loki-service:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'prometheus-uid'
          matcherRegex: 'trace_id=(\w+)'
          name: 'trace_id'
          url: '$${__value.raw}'
    version: 1 