apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: devops-portfolio
  labels:
    app: user-service
    component: backend
    author: dev-shiki
    project-id: PORTFOLIO-DEVOPS-2025-V1
    service-signature: DSK-PORTFOLIO-2025-USER-SVC-K8S-ORIG
  annotations:
    author: "dev-shiki"
    contact: "github.com/dev-shiki"
    project-signature: "DSK-PORTFOLIO-2025-USER-SVC-K8S-ORIG"
    portfolio-purpose: "Professional DevOps Engineering Showcase - User Service"
    tier: microservice
    author: dev-shiki
    project-id: PORTFOLIO-DEVOPS-2025-V1
    portfolio-tag: DevOps-Engineering-Showcase
    service-signature: DSK-PORTFOLIO-2025-USER-SVC-K8S-ORIG
  annotations:
    author: "dev-shiki"
    contact: "github.com/dev-shiki"
    project-signature: "DSK-PORTFOLIO-2025-USER-SVC-K8S-ORIG"
    build-timestamp: "2025-01-27T12:00:00Z"
    project-description: "Enterprise-Grade Cloud-Native Application Delivery Platform"
    portfolio-purpose: "Professional DevOps Engineering Showcase - User Service"
    original-work: "This is an original work created for professional portfolio demonstration"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        component: backend
        tier: microservice
        author: dev-shiki
        project-id: PORTFOLIO-DEVOPS-2025-V1
        service-signature: DSK-PORTFOLIO-2025-USER-SVC-K8S-ORIG
      annotations:
        author: "dev-shiki"
        project-signature: "DSK-PORTFOLIO-2025-USER-SVC-K8S-ORIG"
        portfolio-purpose: "Professional DevOps Engineering Showcase - User Service"
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: devops-portfolio
  labels:
    app: user-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: user-service 