name: SonarCloud

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download dependencies (user-service)
        working-directory: ./user-service
        run: go mod download

      - name: Download dependencies (order-service)
        working-directory: ./order-service
        run: go mod download

      - name: Run tests and coverage (user-service)
        working-directory: ./user-service
        run: |
          go test -v ./... -coverprofile=coverage.out

      - name: Run tests and coverage (order-service)
        working-directory: ./order-service
        run: |
          go test -v ./... -coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 